sudo: required
language: node_js
node_js:
- 10.16.2
cache:
  directories:
  - node_modules
before_script:
  - npm install firebase-tools -g
  - npm run build
script:
  - firebase deploy --only hosting --token "oiyg9B/5BFFf2PQAv8/6XgoQxeFA9Kv+tMEwXpitKwLZc4rkorwkM3G+TQMsE1cB7ETFpdfcDD5YNK/8elWIUkKJuj2cL4swuxfSgE/CQoS3npS0s0dDwuBVQEactJmdGycf/nQC5J8bPqvqDlPRbVksCcm7AuzOCxzSRGuoaV5jeJb87AIMt9OAsEpvLoGm5miu7khugaUv2byBbboP71dI0pQFdqMWMgZz4JzZs6as2QlikZXoy4gSVzQEiwF4evi6gpg/hHFjHt1/j+IJIRYxh2A/NsWGboovTdBkCmB+56AKASMe7eufWhy6ZeTYXRxgx2ODmVB5VkP+HuXZb/QRz3l2e4VLm500a+3zFarOkeWdxt/MKadboWOP6Urnh8LyGaH+CxnjlWd6RbtHOR/a4I/0I8yfi1aNwwfpwPWiV8QMrfIXIKfRIvU+cZ8cox85ACNghq9C8D1La7Q769wJhOPRxTybsWY37Z58h7ym6yuUSbyKgnmcLeBJuHcHZtsBdWx3PMsw0a83pIy176Vkra6l5eD89ZWmtXEphJ8nJ0Tygqaxl7JDLj4Rt8fAQRQxkgU5z7biLY/PHnq1qtU/PzJFe69GSBGs0TES3nwIuIYExFTgmiHYqSuufhm6CGZ76DB18y0nXrsi8qgFqT34CkUGLfZB4LZpyDtNKAY="
