sudo: required
language: node_js
node_js:
- 8.9.1
cache:
  directories:
  - node_modules
before_deploy:
- npm run build
deploy:
- provider: firebase
- project: chat-app
env:
  global:
    FIREBASE_TOKEN: BkF0n6YXBb+xNwA52WoV3gL3muV+WjuX6xlYxtcELZGy762ZxZpSDblq3uqYqmtJ1ZtDqql6C8lKPs3SS8Aya6/QUV/2+IWhxCrJq44gkYUem4xrM6iA3pz+eRhTpkHYMZ58qTkfOZg7mUMhVr1+vizd7kZVvUr8P47Uz/u5X+S3IR/jQmvMG4TmytxGYNY7MZNkvwKsrLosJ66tM/pmyrs9qxM9hM4CPz1vZLngWxbIy9yQswSvi2Jmzu2N/nMVnzKQ7IeyzJlsNzcAoCqbcogJoTshulfmsi7n2JJwcB2DrrujicrAOy39y59wzQtZrb0niPcq6hdW2CZU4AsyL68d1vDkd0JY1MYtWVvao8GgKvHqzVxumJRZ3CvyX/n/kqoO4xztf3Q6+61p7oLzztIk5v+Rv21qXW4zV0BtjC2SSnXzrMM4R/6/dOU7WfWtxfsycbMRl7PwprqOgn84L5+pnNp8KDHv4U9Hg8UuuknLUjdHP1KKjQKk9vdfaaL+qjfNVFf+1+NI/4CP0q30Oxm12uDA9DOqDzMP/ivBS1FYleM5R3sNcmNuA0yZsSM4LXq2Ltavm8pdDY47FVOdz96BPM5FoTr2DaK+84jPm4h91BKfNxc9w8xXurzideT0NlC0y7NKTBv/NmkssKUP3jwaxK+s24Fyjki9jyqHQEo=
